#############################################################################
# Makefile for building: coderesearch
# Generated by qmake (2.01a) (Qt 4.6.3) on: ?? 7? 30 22:30:03 2010
# Project:  coderesearch.pro
# Template: app
# Command: /home/gc/qtsdk-2010.04/qt/bin/qmake -unix -o Makefile coderesearch.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I../../qtsdk-2010.04/qt/mkspecs/linux-g++ -I. -I../../qtsdk-2010.04/qt/include/QtCore -I../../qtsdk-2010.04/qt/include/QtGui -I../../qtsdk-2010.04/qt/include -I. -Ione_obj_class -IptrAndArray -Isqlite -Isearch/search -I.
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/home/gc/qtsdk-2010.04/qt/lib
LIBS          = $(SUBLIBS)  -L/home/gc/qtsdk-2010.04/qt/lib -lQtGui -L/home/gc/qtsdk-2010.04/qt/lib -L/usr/X11R6/lib -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /home/gc/qtsdk-2010.04/qt/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = 1-100-3.c \
		__line__.c \
		animal.cc \
		arr1.cc \
		arr2.cc \
		arr3.cc \
		bird.cc \
		cast.cc \
		cast_const.cc \
		chu.c \
		clock.cc \
		clockm.cc \
		const_object.cc \
		constructor.cc \
		funcarr.cc \
		getchar.c \
		init.cc \
		init_array.cc \
		io.cpp \
		max.c \
		memset.c \
		no_name_object.cc \
		override.cc \
		p.cc \
		sizeof.cc \
		staticint.cc \
		stringsearch.c \
		sunqq.cc \
		time.cc \
		virtual.cc \
		yuefen.cc \
		array/init_array.c \
		linkedList/dlink.c \
		linkedList/node.c \
		memory/malloc.c \
		mulit-thread/create_join_thread.c \
		mulit-thread/thread_run_sametime.c \
		one_obj_class/main.cpp \
		one_obj_class/oneobj.cpp \
		operation/fruit.cc \
		popsamenumber/delarr.c \
		popsamenumber/delete.c \
		popsamenumber/popnum.c \
		printf/hello.c \
		printf/my_printf.c \
		printf/printf.c \
		printf/ptrPrintf.c \
		ptrAndArray/arrName.cc \
		ptrAndArray/arrrows.cc \
		ptrAndArray/intsize.cc \
		ptrAndArray/noname.cc \
		ptrAndArray/qzlx.cc \
		ptrAndArray/strarr.cc \
		ptrAndArray/test1.cc \
		ptrAndArray/test2.cc \
		ptrAndArray/test3.cc \
		ptrAndArray/test4.cc \
		ptrAndArray/test5.cc \
		ptrAndArray/unkarr.cc \
		sqlite/shell.c \
		sqlite/sqlite3.c \
		sqlite/testsqlite3.c \
		struct/struct.c \
		thread/threadcopy.c \
		thread/threadcopy_old.c \
		union/bingEndian.c \
		upAndLower/upandlower.c \
		search/search/common.c \
		search/search/get_email.c \
		search/search/get_image.c \
		search/search/get_link.c \
		search/search/http_get.c \
		search/search/main.c \
		search/search/read_file.c \
		search/search/search_email.c \
		search/search/sqlite_op.c \
		search/search-1/get_email.c \
		search/search-1/get_image.c \
		search/search-1/get_link.c \
		search/search-1/http_get.c \
		search/search-1/search_email.c \
		search/search-1/sqlite_op.c 
OBJECTS       = 1-100-3.o \
		__line__.o \
		animal.o \
		arr1.o \
		arr2.o \
		arr3.o \
		bird.o \
		cast.o \
		cast_const.o \
		chu.o \
		clock.o \
		clockm.o \
		const_object.o \
		constructor.o \
		funcarr.o \
		getchar.o \
		init.o \
		init_array.o \
		io.o \
		max.o \
		memset.o \
		no_name_object.o \
		override.o \
		p.o \
		sizeof.o \
		staticint.o \
		stringsearch.o \
		sunqq.o \
		time.o \
		virtual.o \
		yuefen.o \
		init_array.o \
		dlink.o \
		node.o \
		malloc.o \
		create_join_thread.o \
		thread_run_sametime.o \
		main.o \
		oneobj.o \
		fruit.o \
		delarr.o \
		delete.o \
		popnum.o \
		hello.o \
		my_printf.o \
		printf.o \
		ptrPrintf.o \
		arrName.o \
		arrrows.o \
		intsize.o \
		noname.o \
		qzlx.o \
		strarr.o \
		test1.o \
		test2.o \
		test3.o \
		test4.o \
		test5.o \
		unkarr.o \
		shell.o \
		sqlite3.o \
		testsqlite3.o \
		struct.o \
		threadcopy.o \
		threadcopy_old.o \
		bingEndian.o \
		upandlower.o \
		common.o \
		get_email.o \
		get_image.o \
		get_link.o \
		http_get.o \
		main.o \
		read_file.o \
		search_email.o \
		sqlite_op.o \
		get_email.o \
		get_image.o \
		get_link.o \
		http_get.o \
		search_email.o \
		sqlite_op.o
DIST          = ../../qtsdk-2010.04/qt/mkspecs/common/g++.conf \
		../../qtsdk-2010.04/qt/mkspecs/common/unix.conf \
		../../qtsdk-2010.04/qt/mkspecs/common/linux.conf \
		../../qtsdk-2010.04/qt/mkspecs/qconfig.pri \
		../../qtsdk-2010.04/qt/mkspecs/features/qt_functions.prf \
		../../qtsdk-2010.04/qt/mkspecs/features/qt_config.prf \
		../../qtsdk-2010.04/qt/mkspecs/features/exclusive_builds.prf \
		../../qtsdk-2010.04/qt/mkspecs/features/default_pre.prf \
		../../qtsdk-2010.04/qt/mkspecs/features/release.prf \
		../../qtsdk-2010.04/qt/mkspecs/features/default_post.prf \
		../../qtsdk-2010.04/qt/mkspecs/features/warn_on.prf \
		../../qtsdk-2010.04/qt/mkspecs/features/qt.prf \
		../../qtsdk-2010.04/qt/mkspecs/features/unix/thread.prf \
		../../qtsdk-2010.04/qt/mkspecs/features/moc.prf \
		../../qtsdk-2010.04/qt/mkspecs/features/resources.prf \
		../../qtsdk-2010.04/qt/mkspecs/features/uic.prf \
		../../qtsdk-2010.04/qt/mkspecs/features/yacc.prf \
		../../qtsdk-2010.04/qt/mkspecs/features/lex.prf \
		../../qtsdk-2010.04/qt/mkspecs/features/include_source_dir.prf \
		coderesearch.pro
QMAKE_TARGET  = coderesearch
DESTDIR       = 
TARGET        = coderesearch

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: coderesearch.pro  ../../qtsdk-2010.04/qt/mkspecs/linux-g++/qmake.conf ../../qtsdk-2010.04/qt/mkspecs/common/g++.conf \
		../../qtsdk-2010.04/qt/mkspecs/common/unix.conf \
		../../qtsdk-2010.04/qt/mkspecs/common/linux.conf \
		../../qtsdk-2010.04/qt/mkspecs/qconfig.pri \
		../../qtsdk-2010.04/qt/mkspecs/features/qt_functions.prf \
		../../qtsdk-2010.04/qt/mkspecs/features/qt_config.prf \
		../../qtsdk-2010.04/qt/mkspecs/features/exclusive_builds.prf \
		../../qtsdk-2010.04/qt/mkspecs/features/default_pre.prf \
		../../qtsdk-2010.04/qt/mkspecs/features/release.prf \
		../../qtsdk-2010.04/qt/mkspecs/features/default_post.prf \
		../../qtsdk-2010.04/qt/mkspecs/features/warn_on.prf \
		../../qtsdk-2010.04/qt/mkspecs/features/qt.prf \
		../../qtsdk-2010.04/qt/mkspecs/features/unix/thread.prf \
		../../qtsdk-2010.04/qt/mkspecs/features/moc.prf \
		../../qtsdk-2010.04/qt/mkspecs/features/resources.prf \
		../../qtsdk-2010.04/qt/mkspecs/features/uic.prf \
		../../qtsdk-2010.04/qt/mkspecs/features/yacc.prf \
		../../qtsdk-2010.04/qt/mkspecs/features/lex.prf \
		../../qtsdk-2010.04/qt/mkspecs/features/include_source_dir.prf \
		/home/gc/qtsdk-2010.04/qt/lib/libQtGui.prl \
		/home/gc/qtsdk-2010.04/qt/lib/libQtCore.prl
	$(QMAKE) -unix -o Makefile coderesearch.pro
../../qtsdk-2010.04/qt/mkspecs/common/g++.conf:
../../qtsdk-2010.04/qt/mkspecs/common/unix.conf:
../../qtsdk-2010.04/qt/mkspecs/common/linux.conf:
../../qtsdk-2010.04/qt/mkspecs/qconfig.pri:
../../qtsdk-2010.04/qt/mkspecs/features/qt_functions.prf:
../../qtsdk-2010.04/qt/mkspecs/features/qt_config.prf:
../../qtsdk-2010.04/qt/mkspecs/features/exclusive_builds.prf:
../../qtsdk-2010.04/qt/mkspecs/features/default_pre.prf:
../../qtsdk-2010.04/qt/mkspecs/features/release.prf:
../../qtsdk-2010.04/qt/mkspecs/features/default_post.prf:
../../qtsdk-2010.04/qt/mkspecs/features/warn_on.prf:
../../qtsdk-2010.04/qt/mkspecs/features/qt.prf:
../../qtsdk-2010.04/qt/mkspecs/features/unix/thread.prf:
../../qtsdk-2010.04/qt/mkspecs/features/moc.prf:
../../qtsdk-2010.04/qt/mkspecs/features/resources.prf:
../../qtsdk-2010.04/qt/mkspecs/features/uic.prf:
../../qtsdk-2010.04/qt/mkspecs/features/yacc.prf:
../../qtsdk-2010.04/qt/mkspecs/features/lex.prf:
../../qtsdk-2010.04/qt/mkspecs/features/include_source_dir.prf:
/home/gc/qtsdk-2010.04/qt/lib/libQtGui.prl:
/home/gc/qtsdk-2010.04/qt/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile coderesearch.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/coderesearch1.0.0 || $(MKDIR) .tmp/coderesearch1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/coderesearch1.0.0/ && $(COPY_FILE) --parents static.h one_obj_class/oneobj.h ptrAndArray/extern.h sqlite/sqlite3.h search/search/common.h .tmp/coderesearch1.0.0/ && $(COPY_FILE) --parents 1-100-3.c __line__.c animal.cc arr1.cc arr2.cc arr3.cc bird.cc cast.cc cast_const.cc chu.c clock.cc clockm.cc const_object.cc constructor.cc funcarr.cc getchar.c init.cc init_array.cc io.cpp max.c memset.c no_name_object.cc override.cc p.cc sizeof.cc staticint.cc stringsearch.c sunqq.cc time.cc virtual.cc yuefen.cc array/init_array.c linkedList/dlink.c linkedList/node.c memory/malloc.c mulit-thread/create_join_thread.c mulit-thread/thread_run_sametime.c one_obj_class/main.cpp one_obj_class/oneobj.cpp operation/fruit.cc popsamenumber/delarr.c popsamenumber/delete.c popsamenumber/popnum.c printf/hello.c printf/my_printf.c printf/printf.c printf/ptrPrintf.c ptrAndArray/arrName.cc ptrAndArray/arrrows.cc ptrAndArray/intsize.cc ptrAndArray/noname.cc ptrAndArray/qzlx.cc ptrAndArray/strarr.cc ptrAndArray/test1.cc ptrAndArray/test2.cc ptrAndArray/test3.cc ptrAndArray/test4.cc ptrAndArray/test5.cc ptrAndArray/unkarr.cc sqlite/shell.c sqlite/sqlite3.c sqlite/testsqlite3.c struct/struct.c thread/threadcopy.c thread/threadcopy_old.c union/bingEndian.c upAndLower/upandlower.c search/search/common.c search/search/get_email.c search/search/get_image.c search/search/get_link.c search/search/http_get.c search/search/main.c search/search/read_file.c search/search/search_email.c search/search/sqlite_op.c search/search-1/get_email.c search/search-1/get_image.c search/search-1/get_link.c search/search-1/http_get.c search/search-1/search_email.c search/search-1/sqlite_op.c .tmp/coderesearch1.0.0/ && (cd `dirname .tmp/coderesearch1.0.0` && $(TAR) coderesearch1.0.0.tar coderesearch1.0.0 && $(COMPRESS) coderesearch1.0.0.tar) && $(MOVE) `dirname .tmp/coderesearch1.0.0`/coderesearch1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/coderesearch1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core *.out


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

1-100-3.o: 1-100-3.c 
	$(CC) -c $(CFLAGS) $(INCPATH) -o 1-100-3.o 1-100-3.c

__line__.o: __line__.c 
	$(CC) -c $(CFLAGS) $(INCPATH) -o __line__.o __line__.c

animal.o: animal.cc 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o animal.o animal.cc

arr1.o: arr1.cc 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o arr1.o arr1.cc

arr2.o: arr2.cc 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o arr2.o arr2.cc

arr3.o: arr3.cc 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o arr3.o arr3.cc

bird.o: bird.cc 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bird.o bird.cc

cast.o: cast.cc 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cast.o cast.cc

cast_const.o: cast_const.cc 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cast_const.o cast_const.cc

chu.o: chu.c 
	$(CC) -c $(CFLAGS) $(INCPATH) -o chu.o chu.c

clock.o: clock.cc 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o clock.o clock.cc

clockm.o: clockm.cc 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o clockm.o clockm.cc

const_object.o: const_object.cc 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o const_object.o const_object.cc

constructor.o: constructor.cc 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o constructor.o constructor.cc

funcarr.o: funcarr.cc 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o funcarr.o funcarr.cc

getchar.o: getchar.c 
	$(CC) -c $(CFLAGS) $(INCPATH) -o getchar.o getchar.c

init.o: init.cc 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o init.o init.cc

init_array.o: init_array.cc 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o init_array.o init_array.cc

io.o: io.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o io.o io.cpp

max.o: max.c 
	$(CC) -c $(CFLAGS) $(INCPATH) -o max.o max.c

memset.o: memset.c 
	$(CC) -c $(CFLAGS) $(INCPATH) -o memset.o memset.c

no_name_object.o: no_name_object.cc 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o no_name_object.o no_name_object.cc

override.o: override.cc 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o override.o override.cc

p.o: p.cc 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o p.o p.cc

sizeof.o: sizeof.cc 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sizeof.o sizeof.cc

staticint.o: staticint.cc static.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o staticint.o staticint.cc

stringsearch.o: stringsearch.c 
	$(CC) -c $(CFLAGS) $(INCPATH) -o stringsearch.o stringsearch.c

sunqq.o: sunqq.cc 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sunqq.o sunqq.cc

time.o: time.cc 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o time.o time.cc

virtual.o: virtual.cc 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o virtual.o virtual.cc

yuefen.o: yuefen.cc 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o yuefen.o yuefen.cc

init_array.o: array/init_array.c 
	$(CC) -c $(CFLAGS) $(INCPATH) -o init_array.o array/init_array.c

dlink.o: linkedList/dlink.c 
	$(CC) -c $(CFLAGS) $(INCPATH) -o dlink.o linkedList/dlink.c

node.o: linkedList/node.c 
	$(CC) -c $(CFLAGS) $(INCPATH) -o node.o linkedList/node.c

malloc.o: memory/malloc.c 
	$(CC) -c $(CFLAGS) $(INCPATH) -o malloc.o memory/malloc.c

create_join_thread.o: mulit-thread/create_join_thread.c 
	$(CC) -c $(CFLAGS) $(INCPATH) -o create_join_thread.o mulit-thread/create_join_thread.c

thread_run_sametime.o: mulit-thread/thread_run_sametime.c 
	$(CC) -c $(CFLAGS) $(INCPATH) -o thread_run_sametime.o mulit-thread/thread_run_sametime.c

main.o: one_obj_class/main.cpp one_obj_class/oneobj.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o one_obj_class/main.cpp

oneobj.o: one_obj_class/oneobj.cpp one_obj_class/oneobj.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o oneobj.o one_obj_class/oneobj.cpp

fruit.o: operation/fruit.cc 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fruit.o operation/fruit.cc

delarr.o: popsamenumber/delarr.c 
	$(CC) -c $(CFLAGS) $(INCPATH) -o delarr.o popsamenumber/delarr.c

delete.o: popsamenumber/delete.c 
	$(CC) -c $(CFLAGS) $(INCPATH) -o delete.o popsamenumber/delete.c

popnum.o: popsamenumber/popnum.c 
	$(CC) -c $(CFLAGS) $(INCPATH) -o popnum.o popsamenumber/popnum.c

hello.o: printf/hello.c 
	$(CC) -c $(CFLAGS) $(INCPATH) -o hello.o printf/hello.c

my_printf.o: printf/my_printf.c 
	$(CC) -c $(CFLAGS) $(INCPATH) -o my_printf.o printf/my_printf.c

printf.o: printf/printf.c 
	$(CC) -c $(CFLAGS) $(INCPATH) -o printf.o printf/printf.c

ptrPrintf.o: printf/ptrPrintf.c 
	$(CC) -c $(CFLAGS) $(INCPATH) -o ptrPrintf.o printf/ptrPrintf.c

arrName.o: ptrAndArray/arrName.cc 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o arrName.o ptrAndArray/arrName.cc

arrrows.o: ptrAndArray/arrrows.cc 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o arrrows.o ptrAndArray/arrrows.cc

intsize.o: ptrAndArray/intsize.cc 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o intsize.o ptrAndArray/intsize.cc

noname.o: ptrAndArray/noname.cc 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o noname.o ptrAndArray/noname.cc

qzlx.o: ptrAndArray/qzlx.cc 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qzlx.o ptrAndArray/qzlx.cc

strarr.o: ptrAndArray/strarr.cc 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o strarr.o ptrAndArray/strarr.cc

test1.o: ptrAndArray/test1.cc ptrAndArray/extern.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o test1.o ptrAndArray/test1.cc

test2.o: ptrAndArray/test2.cc 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o test2.o ptrAndArray/test2.cc

test3.o: ptrAndArray/test3.cc 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o test3.o ptrAndArray/test3.cc

test4.o: ptrAndArray/test4.cc 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o test4.o ptrAndArray/test4.cc

test5.o: ptrAndArray/test5.cc 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o test5.o ptrAndArray/test5.cc

unkarr.o: ptrAndArray/unkarr.cc 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o unkarr.o ptrAndArray/unkarr.cc

shell.o: sqlite/shell.c sqlite/sqlite3.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o shell.o sqlite/shell.c

sqlite3.o: sqlite/sqlite3.c 
	$(CC) -c $(CFLAGS) $(INCPATH) -o sqlite3.o sqlite/sqlite3.c

testsqlite3.o: sqlite/testsqlite3.c sqlite/sqlite3.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o testsqlite3.o sqlite/testsqlite3.c

struct.o: struct/struct.c 
	$(CC) -c $(CFLAGS) $(INCPATH) -o struct.o struct/struct.c

threadcopy.o: thread/threadcopy.c 
	$(CC) -c $(CFLAGS) $(INCPATH) -o threadcopy.o thread/threadcopy.c

threadcopy_old.o: thread/threadcopy_old.c 
	$(CC) -c $(CFLAGS) $(INCPATH) -o threadcopy_old.o thread/threadcopy_old.c

bingEndian.o: union/bingEndian.c 
	$(CC) -c $(CFLAGS) $(INCPATH) -o bingEndian.o union/bingEndian.c

upandlower.o: upAndLower/upandlower.c 
	$(CC) -c $(CFLAGS) $(INCPATH) -o upandlower.o upAndLower/upandlower.c

common.o: search/search/common.c 
	$(CC) -c $(CFLAGS) $(INCPATH) -o common.o search/search/common.c

get_email.o: search/search/get_email.c 
	$(CC) -c $(CFLAGS) $(INCPATH) -o get_email.o search/search/get_email.c

get_image.o: search/search/get_image.c search/search/common.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o get_image.o search/search/get_image.c

get_link.o: search/search/get_link.c search/search/common.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o get_link.o search/search/get_link.c

http_get.o: search/search/http_get.c 
	$(CC) -c $(CFLAGS) $(INCPATH) -o http_get.o search/search/http_get.c

main.o: search/search/main.c search/search/common.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o main.o search/search/main.c

read_file.o: search/search/read_file.c 
	$(CC) -c $(CFLAGS) $(INCPATH) -o read_file.o search/search/read_file.c

search_email.o: search/search/search_email.c search/search/common.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o search_email.o search/search/search_email.c

sqlite_op.o: search/search/sqlite_op.c sqlite/sqlite3.h \
		search/search/common.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o sqlite_op.o search/search/sqlite_op.c

get_email.o: search/search-1/get_email.c 
	$(CC) -c $(CFLAGS) $(INCPATH) -o get_email.o search/search-1/get_email.c

get_image.o: search/search-1/get_image.c 
	$(CC) -c $(CFLAGS) $(INCPATH) -o get_image.o search/search-1/get_image.c

get_link.o: search/search-1/get_link.c 
	$(CC) -c $(CFLAGS) $(INCPATH) -o get_link.o search/search-1/get_link.c

http_get.o: search/search-1/http_get.c 
	$(CC) -c $(CFLAGS) $(INCPATH) -o http_get.o search/search-1/http_get.c

search_email.o: search/search-1/search_email.c 
	$(CC) -c $(CFLAGS) $(INCPATH) -o search_email.o search/search-1/search_email.c

sqlite_op.o: search/search-1/sqlite_op.c sqlite/sqlite3.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o sqlite_op.o search/search-1/sqlite_op.c

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

