######################################################################
# Automatically generated by qmake (2.01a) Tue Nov 23 20:12:52 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.c
