#all: five chessboard background fb_init chesspiece mouse
#all: five chessboard background fb_init chesspiece mouse
all:
	gcc chessboard.c background.c five.c fb_init.c chesspiece.c mouse.c
#	gcc $<
.PHONY: clean
clean:
	rm -f *.o a.out
